# Generated by Django 3.1.7 on 2021-05-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaLoai', models.CharField(max_length=30)),
                ('TenLoai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NguonBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaNB', models.CharField(max_length=30)),
                ('TenNB', models.CharField(max_length=100)),
                ('DomainNB', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaSP', models.CharField(max_length=30)),
                ('TenSP', models.CharField(max_length=100)),
                ('MoTa', models.TextField()),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.loaisanpham')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField()),
                ('Gia', models.FloatField()),
                ('GiaCu', models.FloatField()),
                ('UrlImage', models.ImageField(upload_to='')),
                ('MaNB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nguonban')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sanpham')),
            ],
        ),
    ]
