# Generated by Django 3.1.7 on 2021-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='MaNB',
        ),
        migrations.AddField(
            model_name='url',
            name='Domain',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='NguonBan',
        ),
    ]
