# Generated by Django 3.1.7 on 2021-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210503_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='UrlImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
