# Generated by Django 3.1.7 on 2021-05-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210503_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='UrlImage',
            field=models.URLField(null=True),
        ),
    ]
