# Generated by Django 3.1.7 on 2021-05-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210504_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaGoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gia1', models.FloatField(blank=True, null=True)),
                ('Gia2', models.FloatField(blank=True, null=True)),
                ('Gia3', models.FloatField(blank=True, null=True)),
                ('Gia4', models.FloatField(blank=True, null=True)),
                ('Gia5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiaMoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gia1', models.FloatField(blank=True, null=True)),
                ('Gia2', models.FloatField(blank=True, null=True)),
                ('Gia3', models.FloatField(blank=True, null=True)),
                ('Gia4', models.FloatField(blank=True, null=True)),
                ('Gia5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NguonBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNB', models.CharField(max_length=100)),
                ('Domain', models.URLField(null=True)),
                ('Logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenTH', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loaisanpham',
            name='MaLoai',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='MaLoai',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='MaSP',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='MoTa',
        ),
        migrations.RemoveField(
            model_name='url',
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='url',
            name='Gia',
        ),
        migrations.RemoveField(
            model_name='url',
            name='GiaCu',
        ),
        migrations.RemoveField(
            model_name='url',
            name='MaSP',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='LoaiSanPham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.loaisanpham'),
        ),
        migrations.AddField(
            model_name='url',
            name='SanPham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sanpham'),
        ),
        migrations.AlterField(
            model_name='loaisanpham',
            name='TenLoai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ThuocTinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MauSac', models.CharField(blank=True, max_length=100, null=True)),
                ('BoNho', models.CharField(blank=True, max_length=100, null=True)),
                ('GiaGoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.giagoc')),
                ('GiaMoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.giamoi')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ThuongHieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thuonghieu'),
        ),
        migrations.AddField(
            model_name='url',
            name='NguonBan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nguonban'),
        ),
        migrations.AddField(
            model_name='url',
            name='ThuocTinh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thuoctinh'),
        ),
    ]
