# Generated by Django 3.1.7 on 2021-05-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210507_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GiaMoi', models.FloatField(blank=True, null=True)),
                ('GiaGoc', models.FloatField(blank=True, null=True)),
                ('NgayCrawl', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='thuoctinh',
            name='GiaGoc',
        ),
        migrations.RemoveField(
            model_name='thuoctinh',
            name='GiaMoi',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='LoaiSanPham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.loaisanpham'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='TenSP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ThuongHieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thuonghieu'),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='Url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='NguonBan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nguonban'),
        ),
        migrations.AlterField(
            model_name='url',
            name='SanPham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sanpham'),
        ),
        migrations.AlterField(
            model_name='url',
            name='UrlImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thuoctinh',
            name='Gia1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gia'),
        ),
    ]
