# Generated by Django 3.1.7 on 2021-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210514_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaGoc1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaGoc2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaGoc3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaGoc4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaGoc5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaMoi1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaMoi2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaMoi3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaMoi4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thuoctinh',
            name='GiaMoi5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
