# Generated by Django 3.1.7 on 2021-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210604_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
