# Generated by Django 3.1.7 on 2021-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210604_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Url',
            field=models.URLField(unique=True),
        ),
    ]
