# Generated by Django 3.1.7 on 2021-06-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_thuoctinh_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='Url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
