# Generated by Django 3.1.7 on 2021-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210607_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Url',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
