# Generated by Django 3.1.7 on 2021-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210607_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='Url',
            field=models.URLField(unique=True),
        ),
    ]
