# Generated by Django 3.1.7 on 2021-06-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210607_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuoctinh',
            name='Url',
        ),
    ]
