# Generated by Django 3.1.7 on 2021-06-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210608_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoctinh',
            name='NguonBan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nguonban'),
        ),
    ]
