# Generated by Django 3.1.7 on 2021-06-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_thuoctinh_nguonban'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='MoTa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='Tskt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
