# Generated by Django 3.1.7 on 2021-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210617_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguonban',
            name='Logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
