# Generated by Django 3.1.3 on 2021-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210617_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='ImgSP',
            field=models.URLField(blank=True, null=True),
        ),
    ]
