# Generated by Django 3.1.7 on 2021-07-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sanpham_imgsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='NgayKhoiTao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
