# Generated by Django 3.1.3 on 2021-07-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sanpham_ngaykhoitao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='ImgSP',
            field=models.TextField(blank=True, null=True),
        ),
    ]
