# Generated by Django 3.1.3 on 2021-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210729_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguonban',
            name='Logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
