# Generated by Django 3.1.3 on 2021-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210729_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguonban',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
