# Generated by Django 3.1.7 on 2021-06-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoai', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NguonBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNB', models.CharField(max_length=100, unique=True)),
                ('Domain', models.CharField(max_length=100, null=True, unique=True)),
                ('Logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSP', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('LoaiSanPham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.loaisanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenTH', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField(unique=True)),
                ('UrlImage', models.URLField(blank=True, null=True)),
                ('NguonBan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nguonban')),
                ('SanPham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ThuocTinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MauSac', models.CharField(blank=True, max_length=100, null=True)),
                ('BoNho', models.CharField(blank=True, max_length=100, null=True)),
                ('Active', models.BooleanField(blank=True, null=True)),
                ('GiaGoc1', models.FloatField(blank=True, default=0, null=True)),
                ('GiaGoc2', models.FloatField(blank=True, default=0, null=True)),
                ('GiaGoc3', models.FloatField(blank=True, default=0, null=True)),
                ('GiaGoc4', models.FloatField(blank=True, default=0, null=True)),
                ('GiaGoc5', models.FloatField(blank=True, default=0, null=True)),
                ('GiaMoi1', models.FloatField(blank=True, default=0, null=True)),
                ('GiaMoi2', models.FloatField(blank=True, default=0, null=True)),
                ('GiaMoi3', models.FloatField(blank=True, default=0, null=True)),
                ('GiaMoi4', models.FloatField(blank=True, default=0, null=True)),
                ('GiaMoi5', models.FloatField(blank=True, default=0, null=True)),
                ('Ngay1', models.DateField(blank=True, null=True)),
                ('Ngay2', models.DateField(blank=True, null=True)),
                ('Ngay3', models.DateField(blank=True, null=True)),
                ('Ngay4', models.DateField(blank=True, null=True)),
                ('Ngay5', models.DateField(blank=True, null=True)),
                ('SanPham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sanpham')),
                ('Url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.url')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ThuongHieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.thuonghieu'),
        ),
    ]
